# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mL4uVXdy-1CCsWe2bItJZU3IFWdvgppB
"""

import warnings
warnings.filterwarnings("ignore")

import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/andressj1/desarollo_ambiental/main/data.csv")
df1 = pd.read_csv("https://raw.githubusercontent.com/andressj1/desarollo_ambiental/main/turbidez3.csv")
df2 = pd.read_csv("https://raw.githubusercontent.com/andressj1/desarollo_ambiental/main/turbidez2.csv")

####muestra1 de turbidez
plt.figure(figsize=(25, 6))
plt.subplot(1,2,1)
sns.distplot(df.Turbidez)
plt.xlabel('Turbidez')
plt.title('Histograma - Turbidez')
plt.subplot(1,2,2)
df['Turbidez'].plot(kind='box')
plt.title('Boxplot - Turbidez')
plt.show()

####muestra dos de turbidez
plt.figure(figsize=(25, 6))
plt.subplot(1,2,1)
sns.distplot(df2.Turbidez)
plt.xlabel('Turbidez')
plt.title('Histograma - Turbidez')
plt.subplot(1,2,2)
df2['Turbidez'].plot(kind='box')
plt.title('Boxplot - Turbidez')
plt.show()

#### suma de mezcla 1 + mezcla 2
plt.figure(figsize=(25, 6))
plt.subplot(1,2,1)
sns.distplot(df1.Turbidez)
plt.xlabel('Turbidez')
plt.title('Histograma - Turbidez')
plt.subplot(1,2,2)
df1['Turbidez'].plot(kind='box')
plt.title('Boxplot - Turbidez')
plt.show()